services:

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8082"
    depends_on:
      - database-service
    networks:
      - app-network

  database-service:
    build:
      context: .
      dockerfile: ./database-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/talentmatch
      - SPRING_DATASOURCE_USERNAME=talentmatch
      - SPRING_DATASOURCE_PASSWORD=talentmatch
    depends_on:
      - mysql-container
    networks:
      - app-network


  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: talentmatch
      MYSQL_DATABASE: talentmatch
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:

