services:

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database-service

  database-service:
    build:
      context: .
      dockerfile: ./database-service/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/talentmatch
      - SPRING_DATASOURCE_USERNAME=talentmatch
      - SPRING_DATASOURCE_PASSWORD=talentmatch
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: talentmatch
      MYSQL_DATABASE: talentmatch
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
