services:

  api-gateway:
    image: danieldrv/talentmatch-api-gateway:1.1
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - candidate-skill-service
      - mysql-container
    networks:
      - app-network

  user-service:
    image: danieldrv/talentmatch-user-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql-container
    networks:
      - app-network
    restart: unless-stopped

  candidate-skill-service:
   # image: danieldrv/talentmatch-candidate-skill-service:latest
    build:
      context: .
      dockerfile: ./candidateSkill-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql-container
    networks:
      - app-network
    restart: unless-stopped

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: talentmatch
      MYSQL_PASSWORD: talentmatch
      MYSQL_DATABASE: talentmatch
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
