services:

  talentmatch-frontend:
    image: danieldrv/talentmatch-frontend:latest
    ports:
      - "4201:4200"
    networks:
      - app-network

  api-gateway:
    image: danieldrv/talentmatch-api-gateway:latest
  #  build:
   #   context: .
    #  dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - candidate-skill-service
      - projects
      - mysql-container
    networks:
      - app-network

  user-service:
    image: danieldrv/talentmatch-user-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql-container
    networks:
      - app-network
    restart: unless-stopped

  candidate-skill-service:
    image: danieldrv/talentmatch-candidate-skill:latest
 #   build:
  #    context: .
   #   dockerfile: ./candidateSkill-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql-container
    networks:
      - app-network
    restart: unless-stopped

  projects:
    image: danieldrv/talentmatch-projects:latest
   # build:
    #  context: .
     # dockerfile: ./projects/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mysql-container
    networks:
      - app-network
    restart: unless-stopped

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: talentmatch
      MYSQL_PASSWORD: talentmatch
      MYSQL_DATABASE: talentmatch
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
