server:
  port: 8080 # Puerto del API Gateway

spring:
  cloud:
    gateway:
      routes:
        # Rutas para los microservicios
        - id: database_service
          uri: http://localhost:8081 # Puerto donde corre database-service
          predicates:
            - Path=/api/database/**
          filters:
            - StripPrefix=2 # Elimina "/api/database" del path al redirigir

        ###- id: ia_service
    #      uri: http://localhost:8082 # Puerto donde corre el servicio de IA
   #       predicates:
  #          - Path=/api/ia/**
 #           filters:
#              - StripPrefix=2 # Elimina "/api/ia" del path al redirigir
